before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

language: java
jdk: oraclejdk8

language: node_js
node_js:
  - "node"  # Latest Node.js release

install:
  - npm install --prefix client

script:
  - mvn test -q || travis_terminate 2

after_script:
  - ./cc-test-reporter format-coverage -t lcov client/coverage/lcov.info --output "codeclimate.js.json"
  - ./cc-test-reporter sum-coverage --output "codeclimate.combined.json" codeclimate.*.json
  - ./cc-test-reporter upload-coverage --input "codeclimate.combined.json"